name: SANITY
on:
    push:
      branches: [ master ]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: go in the studio
          run: cd /home/runner/work/my-first-liberty-blog/my-first-liberty-blog/studio
        - name: ls
          run: |
               ls -d
               pwd  
