name: Platform Liberty Theme Project Setup
on: [repository_dispatch]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: sanity-io/github-action-sanity@v0.1-alpha
          env:
            repo_name: ${{ github.event.repository.name }}
            SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          with: 
            args: init -y --create-project ${{env.repo_name}} --dataset dbset --output-path temp
        - name: Set env
          run: |
               echo ::set-env name=PROJECT_ID::$(echo PROJECT_ID | jq .api.projectId temp/sanity.json)
               echo ::set-env name=DATASET::$(echo DATASET | jq .api.dataset temp/sanity.json)
               echo ::set-env name=PROJECT_NAME::$(echo PROJECT_NAME | jq .project.name temp/sanity.json)
        - name: Test
          run: |
               sed -i -e 's/"PROJECT_ID"/'$PROJECT_ID'/g' studio/sanity.json
               sed -i -e 's/"DATASET_ID"/'$DATASET'/g' studio/sanity.json
               sed -i -e 's/"PROJECT_NAME"/'$PROJECT_NAME'/g' studio/sanity.json
               sed -i -e 's/"PROJECT_ID"/'$PROJECT_ID'/g' web/.env.production
               sed -i -e 's/"DATASET_ID"/'$DATASET'/g' web/.env.production
               sudo rm -r temp
               sudo rm -r studio/production.tar.gz
               sudo rm -r studio/node_modules
               sudo rm -r .github/workflows/provision.yml
        - name: Commit files
          run: |
                git config --local user.email "platform-services@gmail.com"
                git config --local user.name "Liberty Platform"
                git config advice.addIgnoredFile false
                git add *
                git commit -m "Initial Commit"
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
               github_token: ${{ secrets.REMOTE_GITHUB_TOKEN }}
               repository: ${{ secrets.REMOTE_GITHUB_REPO }}
